"use client";

import { useState } from "react";
import { useToast } from "@/components/site/ToastProvider";
import type { AiReport } from "@/lib/aiReport";

function ListSection({ title, items, emptyLabel }: { title: string; items: string[]; emptyLabel: string }) {
  return (
    <div>
      <h3 className="text-xs font-semibold uppercase tracking-wide text-[var(--color-text-subtle)]">
        {title}
      </h3>
      {items.length === 0 ? (
        <p className="mt-1 text-sm text-[var(--color-text-muted)]">{emptyLabel}</p>
      ) : (
        <ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-[var(--color-text)]">
          {items.map((item, index) => (
            <li key={index}>{item}</li>
          ))}
        </ul>
      )}
    </div>
  );
}

function TextSection({ title, text }: { title: string; text: string }) {
  return (
    <div>
      <h3 className="text-xs font-semibold uppercase tracking-wide text-[var(--color-text-subtle)]">
        {title}
      </h3>
      <p className="mt-1 whitespace-pre-wrap text-sm text-[var(--color-text)]">{text}</p>
    </div>
  );
}

export function AiReportPanel({
  applicationId,
  initialReport,
}: {
  applicationId: string;
  initialReport: AiReport | null;
}) {
  const { showToast } = useToast();
  const [report, setReport] = useState(initialReport);
  const [generating, setGenerating] = useState(false);

  async function handleGenerate() {
    setGenerating(true);
    try {
      const response = await fetch(`/api/admin/applications/${applicationId}/ai-report`, {
        method: "POST",
      });
      const body = await response.json().catch(() => null);

      if (!response.ok) {
        showToast(body?.error ?? "Failed to generate AI report.", "error");
        return;
      }

      setReport(body.report);
      showToast("AI report generated.", "success");
    } catch {
      showToast("Network error — please try again.", "error");
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="card mt-6 p-6">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-lg font-semibold text-[var(--color-text)]">AI Report</h2>
          <p className="field-hint">
            An AI-generated read on this application — one input into your decision, not a verdict.
          </p>
        </div>
        <button
          type="button"
          onClick={handleGenerate}
          disabled={generating}
          className="btn btn-secondary shrink-0"
        >
          {generating ? "Generating…" : report ? "Regenerate" : "Generate AI Report"}
        </button>
      </div>

      {!report ? (
        <p className="text-sm text-[var(--color-text-subtle)]">No AI report generated yet.</p>
      ) : (
        <div className="space-y-4 border-t border-[var(--color-border)] pt-4">
          <TextSection title="Summary" text={report.summary} />
          <TextSection title="Answer Quality" text={report.answerQuality} />
          <ListSection title="Strengths" items={report.strengths} emptyLabel="None noted." />
          <ListSection
            title="Concerns & Red Flags"
            items={report.concerns}
            emptyLabel="None noted."
          />
          <TextSection title="Consistency" text={report.consistencyNotes} />
          <TextSection title="Applicant History" text={report.historyNotes} />
          <p className="text-xs text-[var(--color-text-subtle)]">
            Generated by {report.requestedByName} · {report.model} ·{" "}
            {new Date(report.createdAt).toLocaleString()}
          </p>
        </div>
      )}
    </div>
  );
}
